### ISSUE TITLE
Error returned for correct ISO 3166-1 Alpha-2 code

### ISSUE THREAD

**Issue by AndyHartley1993** [hmrc/interest-restriction-return#279]
Why is this error being generated when the country code of "GB" has been used, surely this is a correct ISO 3166-1 Alpha-2 code?

![image](https://user-images.githubusercontent.com/74418458/118944930-ebd21980-b94c-11eb-85b2-22b072947354.png)

**Comment by JonathanTucker** [comment]
Further, on to this point, there are a couple of "country" codes listed on 
/public/api/conf/1.0/schemas/dereferenced/fullReturnSchema.json
which do not exist in the ISO 3166 international standard

"CS" - apparently stands for Serbia and Montenegro if you google this but they both have their own individual country code which you have also included in your list, Serbia = RS and Montenegro = ME

Then we have the following in your list which are not country codes "EU",  "NT", "TP", "UN"

**Comment by AndyHartley1993** [comment]
In your fullReturnSchema.json located in the dereferenced folder, you have listed out all the ISO 3166-1 Alpha-2 codes.  However, I'm not using the dereferenced schema files, and in the countrycodes.json located here:
/public/api/conf/1.0/schemas/definitions/
All you have is this:

![image](https://user-images.githubusercontent.com/74418458/118954466-b251dc00-b955-11eb-843d-6b7109fe3c3c.png)


I asked in issue #192 I asked if you were going to add the full list of ISO 3166-1 Alpha-2 codes to that schema file, and your reply implied no, but yet in the dereferenced schema file (see above) you have listed the Alpha-2 codes, albeit it in-correctly!

**Comment by burns238** [comment]
Hi,

"GB" is invalid per the business requirements because the country code fields exist for non-UK companies where a UTR is not supplied. Supplying the UTR implies that the UK is the country of incorporation. We will make the error explicit for this here.

@JonathanTucker this is something we noticed recently, there are 4 country codes in our schema that are in transitional reservation after deletion, and 3 that are reserved but don't actually represent countries. We're currently awaiting business approval to remove these values.

@AndyHartley1993 the country codes did previously exist in our schema but were removed because the schema is primarily used to drive our developer-hub documentation and listing all of the country codes under each country field across the endpoints made for particularly untidy documentation. They still exist in the dereferenced schema because the dereferencing script is outdated and is no longer used, thanks for pointing this out and we'll get this tidied up.

I'll leave this issue open until we've resolved the following changes:
- a more explicit error message as to why GB is invalid and that a UTR should be entered instead
- remove the invalid country codes from our validation
- remove the outdated dereferenced schema from the project

**Comment by JonathanTucker** [comment]
Hi
Non-UK incorporation companies can have UTR numbers 
for example, non-resident companies dealing in UK land will have a UTR as they are required to populate the CT600 (from April 2020) - see link below

so how would you expect them to populate the UTR and Country on incorporation inputs in this scenario?


https://www.gov.uk/guidance/register-a-non-resident-company-for-corporation-tax

**Comment by burns238** [comment]
Hi @JonathanTucker, 

It seems that I misunderstood the business requirements behind this. These fields are specifically for company identification, and where a company has a UTR it must be entered, and the Country of Incorporation field is only for the scenario where a UTR can’t be entered. If the Country of Incorporation is GB, a UTR is required which is why this is not an option for the Country of Incorporation.

So in the scenario above we would only expect them to enter the UTR and not the Country of Incorporation.

Cheers,

Mike

**Comment by JonathanTucker** [comment]
Thank you Mike for clarifying 

Jonathan
